# SPDX-License-Identifier: Apache-2.0
# SPDX-FileCopyrightText: 2025 The Linux Foundation

name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"

categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
      - "feat"
  - title: "🐛 Bug Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "🔧 Maintenance"
    labels:
      - "chore"
      - "dependencies"
  - title: "📚 Documentation"
    labels:
      - "documentation"
      - "docs"
  - title: "🔒 Security"
    labels:
      - "security"
  - title: "⚡ Performance"
    labels:
      - "performance"
  - title: "✅ Testing"
    labels:
      - "test"
      - "testing"

change-template: "- $TITLE @$AUTHOR (#$NUMBER)"
change-title-escapes: '\<*_&'

version-resolver:
  major:
    labels:
      - "major"
      - "breaking"
  minor:
    labels:
      - "minor"
      - "feature"
      - "enhancement"
  patch:
    labels:
      - "patch"
      - "fix"
      - "bugfix"
      - "chore"
      - "dependencies"
  default: patch

autolabeler:
  - label: "documentation"
    files:
      - "*.md"
      - "docs/**/*"
  - label: "bug"
    branch:
      - '/fix\/.+/'
    title:
      - "/fix/i"
  - label: "feature"
    branch:
      - '/feat\/.+/'
      - '/feature\/.+/'
    title:
      - "/feat/i"
      - "/feature/i"
  - label: "chore"
    branch:
      - '/chore\/.+/'
    title:
      - "/chore/i"
  - label: "dependencies"
    files:
      - "pyproject.toml"
      - "requirements*.txt"
      - ".github/workflows/*.yaml"
  - label: "testing"
    files:
      - "tests/**/*"
      - ".github/workflows/test*.yaml"

template: |
  ## Changes

  $CHANGES

  ## Contributors

  $CONTRIBUTORS
